require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AnimalSpeciesController do

  # This should return the minimal set of attributes required to create a valid
  # AnimalSpecies. As you add validations to AnimalSpecies, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "common_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AnimalSpeciesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all animal_species as @animal_species" do
      animal_species = AnimalSpecies.create! valid_attributes
      get :index, {}, valid_session
      assigns(:animal_species).should eq([animal_species])
    end
  end

  describe "GET show" do
    it "assigns the requested animal_species as @animal_species" do
      animal_species = AnimalSpecies.create! valid_attributes
      get :show, {:id => animal_species.to_param}, valid_session
      assigns(:animal_species).should eq(animal_species)
    end
  end

  describe "GET new" do
    it "assigns a new animal_species as @animal_species" do
      get :new, {}, valid_session
      assigns(:animal_species).should be_a_new(AnimalSpecies)
    end
  end

  describe "GET edit" do
    it "assigns the requested animal_species as @animal_species" do
      animal_species = AnimalSpecies.create! valid_attributes
      get :edit, {:id => animal_species.to_param}, valid_session
      assigns(:animal_species).should eq(animal_species)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AnimalSpecies" do
        expect {
          post :create, {:animal_species => valid_attributes}, valid_session
        }.to change(AnimalSpecies, :count).by(1)
      end

      it "assigns a newly created animal_species as @animal_species" do
        post :create, {:animal_species => valid_attributes}, valid_session
        assigns(:animal_species).should be_a(AnimalSpecies)
        assigns(:animal_species).should be_persisted
      end

      it "redirects to the created animal_species" do
        post :create, {:animal_species => valid_attributes}, valid_session
        response.should redirect_to(AnimalSpecies.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved animal_species as @animal_species" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalSpecies.any_instance.stub(:save).and_return(false)
        post :create, {:animal_species => { "common_name" => "invalid value" }}, valid_session
        assigns(:animal_species).should be_a_new(AnimalSpecies)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalSpecies.any_instance.stub(:save).and_return(false)
        post :create, {:animal_species => { "common_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested animal_species" do
        animal_species = AnimalSpecies.create! valid_attributes
        # Assuming there are no other animal_species in the database, this
        # specifies that the AnimalSpecies created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AnimalSpecies.any_instance.should_receive(:update).with({ "common_name" => "MyString" })
        put :update, {:id => animal_species.to_param, :animal_species => { "common_name" => "MyString" }}, valid_session
      end

      it "assigns the requested animal_species as @animal_species" do
        animal_species = AnimalSpecies.create! valid_attributes
        put :update, {:id => animal_species.to_param, :animal_species => valid_attributes}, valid_session
        assigns(:animal_species).should eq(animal_species)
      end

      it "redirects to the animal_species" do
        animal_species = AnimalSpecies.create! valid_attributes
        put :update, {:id => animal_species.to_param, :animal_species => valid_attributes}, valid_session
        response.should redirect_to(animal_species)
      end
    end

    describe "with invalid params" do
      it "assigns the animal_species as @animal_species" do
        animal_species = AnimalSpecies.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalSpecies.any_instance.stub(:save).and_return(false)
        put :update, {:id => animal_species.to_param, :animal_species => { "common_name" => "invalid value" }}, valid_session
        assigns(:animal_species).should eq(animal_species)
      end

      it "re-renders the 'edit' template" do
        animal_species = AnimalSpecies.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AnimalSpecies.any_instance.stub(:save).and_return(false)
        put :update, {:id => animal_species.to_param, :animal_species => { "common_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested animal_species" do
      animal_species = AnimalSpecies.create! valid_attributes
      expect {
        delete :destroy, {:id => animal_species.to_param}, valid_session
      }.to change(AnimalSpecies, :count).by(-1)
    end

    it "redirects to the animal_species list" do
      animal_species = AnimalSpecies.create! valid_attributes
      delete :destroy, {:id => animal_species.to_param}, valid_session
      response.should redirect_to(animal_species_index_url)
    end
  end

end
