require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompositeNetworkMembersController do

  # This should return the minimal set of attributes required to create a valid
  # CompositeNetworkMember. As you add validations to CompositeNetworkMember, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CompositeNetworkMembersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all composite_network_members as @composite_network_members" do
      composite_network_member = CompositeNetworkMember.create! valid_attributes
      get :index, {}, valid_session
      assigns(:composite_network_member).should eq([composite_network_member])
    end
  end

  describe "GET show" do
    it "assigns the requested composite_network_member as @composite_network_member" do
      composite_network_member = CompositeNetworkMember.create! valid_attributes
      get :show, {:id => composite_network_member.to_param}, valid_session
      assigns(:composite_network_member).should eq(composite_network_member)
    end
  end

  describe "GET new" do
    it "assigns a new composite_network_member as @composite_network_member" do
      get :new, {}, valid_session
      assigns(:composite_network_member).should be_a_new(CompositeNetworkMember)
    end
  end

  describe "GET edit" do
    it "assigns the requested composite_network_member as @composite_network_member" do
      composite_network_member = CompositeNetworkMember.create! valid_attributes
      get :edit, {:id => composite_network_member.to_param}, valid_session
      assigns(:composite_network_member).should eq(composite_network_member)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompositeNetworkMember" do
        expect {
          post :create, {:composite_network_member => valid_attributes}, valid_session
        }.to change(CompositeNetworkMember, :count).by(1)
      end

      it "assigns a newly created composite_network_member as @composite_network_member" do
        post :create, {:composite_network_member => valid_attributes}, valid_session
        assigns(:composite_network_member).should be_a(CompositeNetworkMember)
        assigns(:composite_network_member).should be_persisted
      end

      it "redirects to the created composite_network_member" do
        post :create, {:composite_network_member => valid_attributes}, valid_session
        response.should redirect_to(CompositeNetworkMember.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved composite_network_member as @composite_network_member" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompositeNetworkMember.any_instance.stub(:save).and_return(false)
        post :create, {:composite_network_member => {  }}, valid_session
        assigns(:composite_network_member).should be_a_new(CompositeNetworkMember)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompositeNetworkMember.any_instance.stub(:save).and_return(false)
        post :create, {:composite_network_member => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested composite_network_member" do
        composite_network_member = CompositeNetworkMember.create! valid_attributes
        # Assuming there are no other composite_network_member in the database, this
        # specifies that the CompositeNetworkMember created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompositeNetworkMember.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => composite_network_member.to_param, :composite_network_member => { "these" => "params" }}, valid_session
      end

      it "assigns the requested composite_network_member as @composite_network_member" do
        composite_network_member = CompositeNetworkMember.create! valid_attributes
        put :update, {:id => composite_network_member.to_param, :composite_network_member => valid_attributes}, valid_session
        assigns(:composite_network_member).should eq(composite_network_member)
      end

      it "redirects to the composite_network_member" do
        composite_network_member = CompositeNetworkMember.create! valid_attributes
        put :update, {:id => composite_network_member.to_param, :composite_network_member => valid_attributes}, valid_session
        response.should redirect_to(composite_network_member)
      end
    end

    describe "with invalid params" do
      it "assigns the composite_network_member as @composite_network_member" do
        composite_network_member = CompositeNetworkMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompositeNetworkMember.any_instance.stub(:save).and_return(false)
        put :update, {:id => composite_network_member.to_param, :composite_network_member => {  }}, valid_session
        assigns(:composite_network_member).should eq(composite_network_member)
      end

      it "re-renders the 'edit' template" do
        composite_network_member = CompositeNetworkMember.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompositeNetworkMember.any_instance.stub(:save).and_return(false)
        put :update, {:id => composite_network_member.to_param, :composite_network_member => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested composite_network_member" do
      composite_network_member = CompositeNetworkMember.create! valid_attributes
      expect {
        delete :destroy, {:id => composite_network_member.to_param}, valid_session
      }.to change(CompositeNetworkMember, :count).by(-1)
    end

    it "redirects to the composite_network_member list" do
      composite_network_member = CompositeNetworkMember.create! valid_attributes
      delete :destroy, {:id => composite_network_member.to_param}, valid_session
      response.should redirect_to(composite_network_members_url)
    end
  end

end
