require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HuntingPlotUserAccessesController do

  # This should return the minimal set of attributes required to create a valid
  # HuntingPlotUserAccess. As you add validations to HuntingPlotUserAccess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HuntingPlotUserAccessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all hunting_plot_user_accesses as @hunting_plot_user_accesses" do
      hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hunting_plot_user_access).should eq([hunting_plot_user_access])
    end
  end

  describe "GET show" do
    it "assigns the requested hunting_plot_user_access as @hunting_plot_user_access" do
      hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
      get :show, {:id => hunting_plot_user_access.to_param}, valid_session
      assigns(:hunting_plot_user_access).should eq(hunting_plot_user_access)
    end
  end

  describe "GET new" do
    it "assigns a new hunting_plot_user_access as @hunting_plot_user_access" do
      get :new, {}, valid_session
      assigns(:hunting_plot_user_access).should be_a_new(HuntingPlotUserAccess)
    end
  end

  describe "GET edit" do
    it "assigns the requested hunting_plot_user_access as @hunting_plot_user_access" do
      hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
      get :edit, {:id => hunting_plot_user_access.to_param}, valid_session
      assigns(:hunting_plot_user_access).should eq(hunting_plot_user_access)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HuntingPlotUserAccess" do
        expect {
          post :create, {:hunting_plot_user_access => valid_attributes}, valid_session
        }.to change(HuntingPlotUserAccess, :count).by(1)
      end

      it "assigns a newly created hunting_plot_user_access as @hunting_plot_user_access" do
        post :create, {:hunting_plot_user_access => valid_attributes}, valid_session
        assigns(:hunting_plot_user_access).should be_a(HuntingPlotUserAccess)
        assigns(:hunting_plot_user_access).should be_persisted
      end

      it "redirects to the created hunting_plot_user_access" do
        post :create, {:hunting_plot_user_access => valid_attributes}, valid_session
        response.should redirect_to(HuntingPlotUserAccess.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hunting_plot_user_access as @hunting_plot_user_access" do
        # Trigger the behavior that occurs when invalid params are submitted
        HuntingPlotUserAccess.any_instance.stub(:save).and_return(false)
        post :create, {:hunting_plot_user_access => {  }}, valid_session
        assigns(:hunting_plot_user_access).should be_a_new(HuntingPlotUserAccess)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HuntingPlotUserAccess.any_instance.stub(:save).and_return(false)
        post :create, {:hunting_plot_user_access => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hunting_plot_user_access" do
        hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
        # Assuming there are no other hunting_plot_user_access in the database, this
        # specifies that the HuntingPlotUserAccess created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HuntingPlotUserAccess.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => hunting_plot_user_access.to_param, :hunting_plot_user_access => { "these" => "params" }}, valid_session
      end

      it "assigns the requested hunting_plot_user_access as @hunting_plot_user_access" do
        hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
        put :update, {:id => hunting_plot_user_access.to_param, :hunting_plot_user_access => valid_attributes}, valid_session
        assigns(:hunting_plot_user_access).should eq(hunting_plot_user_access)
      end

      it "redirects to the hunting_plot_user_access" do
        hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
        put :update, {:id => hunting_plot_user_access.to_param, :hunting_plot_user_access => valid_attributes}, valid_session
        response.should redirect_to(hunting_plot_user_access)
      end
    end

    describe "with invalid params" do
      it "assigns the hunting_plot_user_access as @hunting_plot_user_access" do
        hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HuntingPlotUserAccess.any_instance.stub(:save).and_return(false)
        put :update, {:id => hunting_plot_user_access.to_param, :hunting_plot_user_access => {  }}, valid_session
        assigns(:hunting_plot_user_access).should eq(hunting_plot_user_access)
      end

      it "re-renders the 'edit' template" do
        hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HuntingPlotUserAccess.any_instance.stub(:save).and_return(false)
        put :update, {:id => hunting_plot_user_access.to_param, :hunting_plot_user_access => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hunting_plot_user_access" do
      hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
      expect {
        delete :destroy, {:id => hunting_plot_user_access.to_param}, valid_session
      }.to change(HuntingPlotUserAccess, :count).by(-1)
    end

    it "redirects to the hunting_plot_user_access list" do
      hunting_plot_user_access = HuntingPlotUserAccess.create! valid_attributes
      delete :destroy, {:id => hunting_plot_user_access.to_param}, valid_session
      response.should redirect_to(hunting_plot_user_accesses_url)
    end
  end

end
